### ISSUE TITLE
User can view Pokedex list

### ISSUE THREAD

**Issue by K-Bowler** [K-Bowler/ajax-project#1]
## 📐 Functionality
User will be able to view the list of all Pokemon in a list.

## 🖼️ Wireframes
![image](https://user-images.githubusercontent.com/43438792/164123912-0ad99873-7f70-406b-8cf2-12cb27192666.png)
![image](https://user-images.githubusercontent.com/43438792/164123979-132a3c87-49de-4cbb-8fb7-dd45ec7661fc.png)

![image](https://user-images.githubusercontent.com/43438792/164121312-1331a9ab-92c1-4539-ac50-a779f66ab202.png)
![image](https://user-images.githubusercontent.com/43438792/164121344-53bb96e5-f447-409a-853b-9a82ff01eadf.png)

## ✅ Task List

- [ ] Complete HTML / CSS for Pokedex and main menu
- [ ] Get Pokemon names from the 'PokeAPI'
- [ ] Get names to fill in <li> elements to make a list of Pokemon names 
- [ ] Clean Up
