### ISSUE TITLE
User can search for a Pokemon by name in the Pokedex:

### ISSUE THREAD

**Issue by K-Bowler** [K-Bowler/ajax-project#2]
## 📐 Functionality
  User can search for a Pokémon by name in the Pokedex. User can use the search bar provided to search for a Pokémon in the list and will move the pokedex list to the Pokémon that they are searching for.

## 🖼️ Wireframes
![image](https://user-images.githubusercontent.com/43438792/156239089-717018ba-fcdb-42d9-b0e7-b3a0d2934697.png)
![image](https://user-images.githubusercontent.com/43438792/156239621-bf00c87c-55a2-4780-b828-dffc898b7fcb.png)

## ✅ Task List

- [ ] Create search functionality 
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
