### ISSUE TITLE
User can view Pokémon entries in pokedex list

### ISSUE THREAD

**Issue by K-Bowler** [K-Bowler/ajax-project#3]
## 📐 Functionality
  User can click/ tap on Pokedex entry, and will switch to the entry screen.
## 🖼️ Wireframes
![image](https://user-images.githubusercontent.com/43438792/156244840-b78ca43c-8c64-4dcb-8e46-5c5b003b6316.png)
![image](https://user-images.githubusercontent.com/43438792/156244867-53e4e537-172f-482f-ac24-97d1d10bbbae.png)

## ✅ Task List

- [ ] Pokedex list entries act as buttons to bring user to the Pokemon entry
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
