### ISSUE TITLE
#4 User can create a trainer card that has their team on it (teams are made of six pokemon chosen from the pokedex)

### ISSUE THREAD

**Issue by K-Bowler** [K-Bowler/ajax-project#4]
## 📐 Functionality
  User can add a Pokémon to their trainer card to create their team.

## 🖼️ Wireframes
![image](https://user-images.githubusercontent.com/43438792/156246430-7f565ea6-cec3-4448-9596-f1ace124de4d.png)
![image](https://user-images.githubusercontent.com/43438792/156246487-a6096ec7-fbe7-42bd-9086-aeaa6563c2de.png)
![image](https://user-images.githubusercontent.com/43438792/156246564-58dec416-c21c-4983-8295-2a0e56a45814.png)

## ✅ Task List

- [ ] User can add Pokémon from the Pokedex to their trainer cards to make a team
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
