### ISSUE TITLE
User can customize trainer card

### ISSUE THREAD

**Issue by K-Bowler** [K-Bowler/ajax-project#5]
## 📐 Functionality
  User can select a background they want for their trainer card out of a selection of pre-selected options.

## 🖼️ Wireframes
![image](https://user-images.githubusercontent.com/43438792/156248094-d07a9e67-46ea-4421-8cc0-fbb712a13ed5.png)
![image](https://user-images.githubusercontent.com/43438792/156248152-85e8f85b-41e5-4803-8b05-9b544b79d378.png)
![image](https://user-images.githubusercontent.com/43438792/156249310-dcc36233-0105-486d-a647-e1e1fd10d001.png)
![image](https://user-images.githubusercontent.com/43438792/156250536-445ed708-1177-4857-9991-7f66993e7d1c.png)
![image](https://user-images.githubusercontent.com/43438792/156250601-753459cf-66e2-4179-b26c-9faac768a182.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] Make a list of options of backgrounds
- [ ] User can select out of the backgrounds provided to change their trainer card background
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
